# Generated by Django 3.2.12 on 2023-05-04 18:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


def add_user_profiles(apps, schema_editor):
    users = apps.get_model('authapp', 'User')
    profiles = apps.get_model('authapp', 'ShopUserProfile')
    for user in users.objects.all():
        user_profile = profiles.objects.create(user=user)
        user_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20230404_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 18, 35, 56, 934105, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=18, null=True),
        ),
        migrations.CreateModel(
            name='ShopUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=128, verbose_name='теги')),
                ('aboutMe', models.TextField(blank=True, max_length=512, verbose_name='о себе')),
                ('gender', models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж')], max_length=1, verbose_name='пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(add_user_profiles),
    ]
