# Generated by Django 3.2.12 on 2023-05-11 14:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20230504_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 14, 32, 12, 777655, tzinfo=utc)),
        ),
    ]
